version: "3.9"
services:
  heavensboard-project-service-postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: "project_service"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5436:5432"
